openeuropa/bootstrap-component-library

src/components/alert/alert.html.twig
src/components/alert/alert.story.js
src/components/alert/alert.test.js
storybook/package.json
yarn.lock

I've found an existing implementation of the drupal attributes in twing made by the same author, it seems to work as close as possible to the drupal implementation, as it is, in general, for how twing implements twig-php.
I made an example on the alert component, we would then refactor all the components to apply this new approach.

chore(attributes): Using drupal attributes in the alert component

---

src/components/blockquote/blockquote.html.twig
src/components/blockquote/blockquote.test.js
src/components/button/__snapshots__/button.test.js.snap
src/components/button/button.html.twig
src/components/button/button.story.js
src/components/button/button.test.js
src/components/header/__snapshots__/header.test.js.snap
src/components/icon/icon.html.twig
src/components/link/__snapshots__/link.test.js.snap
src/components/link/link.html.twig
src/components/link/link.story.js
src/components/link/link.test.js
src/components/modal/__snapshots__/modal.test.js.snap
src/components/modal/modal.html.twig
src/components/spinner/spinner.html.twig
src/components/spinner/spinner.test.js
src/components/table/table.html.twig
src/components/table/table.test.js
src/data/blockquote/data.js
src/data/button/spinnerData.js
src/data/header/data.js
src/data/icon/data.js
src/data/modal/data.js
src/data/pagination/dataCustomIcons.js
src/data/spinner/data.js
src/data/table/data.js

Components refactored modal,icon,blockquote,spinners,table with drupal attributes

feat(drupal-attributes): Drupal attributes for multiple components - FRONT-2408

---

src/components/accordion/accordion.html.twig
src/components/accordion/accordion.story.js
src/components/badge/badge.html.twig
src/components/badge/badge.story.js
src/components/badge/badge.test.js
src/components/dropdown/dropdown.html.twig
src/components/dropdown/dropdown.story.js
src/components/dropdown/dropdown.test.js
src/components/list-group/__snapshots__/list-group.test.js.snap
src/components/list-group/list-group.html.twig
src/components/list-group/list-group.story.js
src/components/navigation/navigation.html.twig
src/components/offcanvas/offcanvas.html.twig
src/components/offcanvas/offcanvas.story.js
src/components/offcanvas/offcanvas.test.js
src/data/accordion/data.js
src/data/badge/data.js
src/data/dropdown/data.js
src/data/list-group/actionableData.js
src/data/list-group/data.js
src/data/list-group/orderedData.js
src/data/offcanvas/data.js

Refactored components using drupal attributes: accordion, badge, list-group, dropdown, offcanvas.

feat(drupal-attributes): Refactored multiple components - FRONT-2419

---

src/components/bcl-carousel/carousel.html.twig
src/components/bcl-carousel/carousel.story.js
src/components/bcl-carousel/carousel.test.js

This was done to keep the alignment with the drupal image structure.

feat(image structure): Added parse image in carousel for drupal structure of images - FRONT-2591

---

src/components/bcl-blockquote/blockquote.story.js
src/components/bcl-card-layout/card-layout.story.js
src/components/bcl-table/table.story.js
src/compositions/bcl-content-banner/content-banner.story.js
src/compositions/bcl-fact-figures/fact-figures.story.js
src/compositions/bcl-search-form/search-form.story.js
src/themes/ucpkn/src/scss/base/_variables.scss

I tried changing 
$component-active-bg
but it's not working being passed to a variable and that variable being used to set each individual component focus state. This is the only way i could make it work.

fix(ucpkn-variables): Added fix for variables and fix for crashing stories - OEL-893

---

src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
src/compositions/bcl-timeline/dataDefault.js
static/index.html

I noticed that the file name of the icons used for the timeline is also incorrect

chore: Fix wrong library title - OEL-916

---

src/components/bcl-carousel/carousel.html.twig
src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
src/compositions/bcl-gallery/data/data.js
src/compositions/bcl-gallery/gallery-item.html.twig
src/compositions/bcl-gallery/gallery-modal.html.twig
src/compositions/bcl-gallery/gallery.html.twig
src/compositions/bcl-gallery/gallery.test.js
src/compositions/bcl-project/__snapshots__/project.test.js.snap

Reverts openeuropa/bootstrap-component-library#479

Revert "feat(gallery): Raw filter used and fixed more items - OEL-2093"

---

src/themes/default/src/scss/_multiselect.scss

feat(multiselect): Fixed multiselect overflow. - OEL-2784

---

src/components/bcl-offcanvas/offcanvas.html.twig

OEL-2731: Fix offcanvas boolean parameters.

---

bootstrap/package.json
bootstrap/replace-icons/twitter.svg

OEL-3066: Replaced twitter icon.

---

src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
src/compositions/bcl-links-block/links-block.html.twig
src/compositions/bcl-links-block/links-block.story.js
src/compositions/bcl-links-block/links-block.test.js

OEL-2793: Check for links block if links are not present.

---

builder/scripts/styles.js
src/themes/default/bcl-builder.config.js

OEL-3382: Styles css prefixer flexibility.

---

src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
src/compositions/bcl-event/__snapshots__/event.test.js.snap
src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
src/compositions/bcl-group/__snapshots__/group.test.js.snap
src/compositions/bcl-header/__snapshots__/header.test.js.snap
src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
src/compositions/bcl-language-list/language-list-modal.html.twig
src/compositions/bcl-news/__snapshots__/news.test.js.snap
src/compositions/bcl-page/__snapshots__/page.test.js.snap
src/compositions/bcl-person/__snapshots__/person.test.js.snap
src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
src/compositions/bcl-project/__snapshots__/project.test.js.snap
src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
src/compositions/bcl-search/__snapshots__/search.test.js.snap
src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
src/compositions/bcl-user/__snapshots__/user.test.js.snap
src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
src/themes/default/src/scss/_header.scss

OEL-3423: Changed language list modal title tag to div.

---

src/themes/default/src/scss/_multiselect.scss

OEL-3414: Changed color of the multiselect placeholder.

---

src/themes/default/src/scss/_blockquote.scss
src/themes/default/src/scss/oe-bcl-default.scss

OEL-3415: Fixed blockqoute footer color.

---

src/components/bcl-carousel/__snapshots__/carousel.test.js.snap
src/components/bcl-carousel/carousel.html.twig
src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
src/compositions/bcl-project/__snapshots__/project.test.js.snap
src/themes/default/src/scss/_carousel.scss

OEL-3462: Carousel focus state.

---

src/themes/default/src/scss/_accordion.scss
src/themes/default/src/scss/oe-bcl-default.scss

OEL-3407: Added focus state on accordion.

---

src/themes/default/src/scss/_pagination.scss

OEL-3403: Pagination focus.

---

src/themes/default/src/scss/_badge.scss

OEL-3404: Badges focus state.

---

src/themes/default/src/scss/_button.scss
src/themes/default/src/scss/_language-list.scss

OEL-3400: Button focus state.

---

src/themes/default/src/scss/_tabs.scss

OEL-3406: Tabs focus state.

---

src/compositions/bcl-header/__snapshots__/header.test.js.snap
src/compositions/bcl-header/header.html.twig
src/themes/default/src/scss/_header.scss

OEL-3402: Menu focus state.

---

src/themes/default/src/scss/_input.scss

OEL-3401: Input focus state.

---

src/themes/default/src/js/accessible-toggle/accessible-toggle.js

OEL-3552: Fixed js accessible case.
